version: "3"

services:
    php:
        build: ./docker/php
        container_name: app
        tty: true
        volumes:
            - ./www:/home/www
            - ./docker/php/php.ini:/usr/local/etc/conf.d/local.ini

    server:
        build: ./docker/nginx
        container_name: server
        tty: true
        ports:
            - "7777:80"
            - "443:443"
        volumes:
            - ./www:/home/www
            - ./docker/logs/nginx:/var/log/nginx

    db:
        image: postgres:13
        container_name: db
        tty: true
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        volumes:
            - ./docker/logs/postgresql:/var/log/postgresql
            - ./docker/dbdata:/var/lib/postgresql/data
